project:
  type: website

website:
  title: "Summary"

  
  sidebar:
    - id: "tasks" 
      title: "summary"
      contents:
        - text: "Sections"
        - "education.qmd"
        - "experience.qmd"
        - "freelance.qmd"
  
  page-footer: 
    background: dark
    center: "it does not matter how slowly you go so long as you do not stop (Confucios)" 
    right: 
      - icon: github
        href: https://github.com/rarmero
      - icon: linkedin 
        href: https://es.linkedin.com/in/rafaelcarrion 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

