---
title: "Education"
format: html
categories: [scrum, softskills, software]
---

## CIFO La Violeta - Barcelona (Sept/22 - July/2023)

[Course documentation](https://rarmero.github.io/appwebcifolavioleta){.external}

- App web. Java, SpringBoot, React. (550h)
- Devops.(100h)
- Scrum. (200h)

## Microsoft Learning (Juny-Sept 2022)

:::{.callout-warning title="Notice"}
Only reading, not certificate
:::


### Software Engineering

1. Microservices with .Net an Asp.Net Core.
2. Web apps and services with Asp.net core, API and .Net.
3. Build .Net app with C#
4. Get started on a DevOps transformation journey
5. Az-900
6. Introduction a React.
7. AI-900
8. PL-900
9. Introduction to Asp.net SignalR

### Data science

- Azure Synapse Analytics
- DP-203 Ingeniería de datos con Azure
- DP-100 Ciencia de datos con Azure
- Power BI
- Python


## Altran (03/2017- 10/2018)

### Soft Skills

-  The communication: the conversation, 10h
-  Decision making , 8h
-  Emotional and Situational Intelligence, 10h
-  Resilence management, 8h

## Technical courses.

- JIRA Admin, 20h
- Developing Microsoft Azure Solutions (20-532)
- Software testing ISTQB
- Requirements analysis, 10h


## English
- goFluent, 18 h (B2)
- MyOxford English, 40h (B1)


## Mobile (feb. de 2014 - mar. de 2015)

- ios, android and windows

## Others

- Diciembre del 2002: curso de domótica, de 260 h, en Sauter Ibérica, S. A.
- CNAP de Cisco.(sistemas operativos de red - routers)

## Main

- BUP- COU.
- CFGS Desarrollo de Aplicaciones Informáticas. 1996
- Ingeniería técnica de Gestión - UOC
  (in the absence of three first-year subjects and the final degree project)

  Attendend from 1999 to 2005

# Languages

- Español: lengua materna.
- Català: llegit i parlat, nivell alt. Escrit, mitjà.
- English: reading, high. write, middle. Talk, middle.
- Français: lecture seulement, niveau faible.
- Deutsch: starting.


# Technical knowledge

- C#, ASP, ASP.NET, VB, VB.NET, Java, C++
- .Net , SpringBoot
- JS, Blazor, Razor, React, Angular.
- XML, JSON.
- MVC, Web API.
- DDD, Design Patterns, Entity Framework.
- LINQ,T-SQL, SQL Server, Oracle, MySQL, MongoDB
- Unit Testing. TDD.
- Mobile: IOS, Android.
- Cloud : AWS, Azure.
- Devops : AWS, Github Actions.